version: '3.8'

services:
  db: 
    image: mongo:latest
    container_name: mongodb
    env_file:
      - ./env/db.env
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - node-network

  api:
    image: node-api-img
    container_name: node-api
    restart: always
    ports:
      - 3000:3000
    networks:
      - node-network
volumes: 
  mongodb_data:

networks:
  node-network: